apiVersion: v1
kind: Service
metadata:
  name: kibana-loadbalancer
  namespace: kube-logging
spec:
  selector:
    app: kibana
  ports:
  - name: http
    port: 80
    targetPort: 5601
  type: LoadBalancer
